services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:  
      - .:/usr/src/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  redis-data:
  db-data:
